### ISSUE TITLE
Detect if browser cannot use API

### ISSUE THREAD

**Issue by SlyAceZeta** [BellCubeDev/fomod-builder#1]
I realize this builder isn't exactly ready for prime-time yet (many missing features, especially regarding flags) but it would be helpful to display an error to the user if their browser is not supported due to lacking the API calls necessary for working with folders.

**Comment by BellCubeDev** [comment]
Could've sworn I'd implemented that. Thank you for telling me I hadn't!

I plan to have other ways to work with an installer in the future so the lack of API support hopefully won't be as huge of a problem as it is currently.

The builder actually already detects if a given loader can be used. I guess it just wasn't really used.
